import type { NextPage } from 'next'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const router = useRouter()

  const handleGoMore = () => {

    router.push({ pathname: '/demo', query: { a: 'hahha', b: '233' } })
    // router.push('/dynamic/single/[id]', '/dynamic/single/2')
    // router.push('/dynamic/more/[...id]', '/dynamic/more/1/2')


  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        
        <Link href={{pathname: '/demo1',query: {a: 10, b: 20, name: 'next'},}}>demo1</Link>
        <Link href="/dynamic/single/[id]" as="/dynamic/single/20">单参数动态路由</Link>
        <Link href="/dynamic/more/[...id]" as="/dynamic/more/20/21">多参数动态路由</Link>
        <Link href="/dynamic/song" >song page</Link>
        <Link href="/demo-api">API 路由</Link>
        <Link href="/sass-demo">sass-demo</Link>
        <Link href="/data-fetch/static-props">static-props</Link>
        <Link href="/data-fetch/server-props">server-props</Link>
        <Link href="/data-fetch/static-paths/[pid]" as="/data-fetch/static-paths/1">path1</Link>
        <Link href="/data-fetch/static-paths/[pid]" as="/data-fetch/static-paths/2">path2</Link>
        <Link href="/data-fetch/static-paths/[pid]" as="/data-fetch/static-paths/3">path3</Link>

        <Link href="/data-fetch/static-path-props/[pid]" as="/data-fetch/static-path-props/1">static-path-props</Link>
        <Link href="/data-fetch/static-props1">server-props1111</Link>
        <button onClick={handleGoMore}>多参数动态路由</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
